### ISSUE TITLE
배포자동화 구축

### ISSUE THREAD

**Issue by yooyouny** [yooyouny/PostFeed#4]
### 📄 Describe

github actions, Jenkins, AWS EC2를 활용한 배포 자동화 구축 
- develop에 머지 시 github actions에서 테스트 진행 
- main에 머지 시 jenkins 서버에서 빌드 진행 
- jenkins 서버에서 빌드 후 운영 서버에 배포  

### ✅ Tasks

- [ ] github actions 설정
- [ ] jenkins 설치 및 설정 
- [ ] 운영서버 설치 및 설정
